# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Porcentaje.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(150, 111)
        widget.setMinimumSize(QtCore.QSize(150, 111))
        widget.setMaximumSize(QtCore.QSize(150, 111))
        widget.setStyleSheet("QPushButton{\n"
"border-radius:5px;\n"
"border:1px solid #167;}\n"
"QSpinBox{\n"
"border:1px solid #167;}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinBox = QtWidgets.QSpinBox(widget)
        self.spinBox.setStyleSheet("border-radius:5px;")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton_determinar = QtWidgets.QPushButton(widget)
        self.pushButton_determinar.setStyleSheet("QPushButton{\n"
"border:1px solid #ffffff;\n"
"background-color: #ffffff;}\n"
"\n"
"QPushButton:hover{\n"
"border-color:#167;}")
        self.pushButton_determinar.setObjectName("pushButton_determinar")
        self.verticalLayout.addWidget(self.pushButton_determinar)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Porcentaje"))
        self.pushButton_determinar.setText(_translate("widget", "Determinar"))
